.TH EAT 1 "27 March 2022"
.SH NAME
eat \- the package manager for Linux

.SH SYNOPSIS
eatinst package [-h],
eathelp

.SH DESCRIPTION
eat is a package manager that installs programs without touching the actual Linux system. It downloads
and installs programs from YAML manifests. It extracts the YAML manifest and gets out the metadata
of the application, and adds it to your PATH.

.SH ARGUMENTS
eatinst
  Optional
    -h: Display help message
  Positional
    target: what to install

.SH CONTRIBUTE
Eat is released to the public under the GNU General Public License, along with it's
sources.
        
Help contribute to Eat and the free software domain by adding new manifests to the sources
(https://github.com/Tyler887/eat-network), and report bugs (https://github.com/Tyler887/eat/issues).
        
.SH COPYRIGHT
The eat package manager is under the GNU GPLv3, and this document is under the GNU All-Permissive
License.
